# Generated by Django 3.1.6 on 2021-05-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
