# Generated by Django 3.1.6 on 2021-05-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0003_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='KeyId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.unit'),
        ),
    ]
