# Generated by Django 3.1.6 on 2021-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0004_item_keyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('psw', models.TextField(default='')),
                ('repeat', models.TextField(default='')),
                ('fname', models.TextField(default='')),
                ('lname', models.TextField(default='')),
                ('age', models.TextField(default='')),
                ('sex', models.TextField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='unit',
            new_name='LogIn',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
