# Generated by Django 3.1.6 on 2021-06-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0006_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('CurrentWeight', models.TextField(default='')),
                ('Remarks', models.TextField(default='')),
                ('SignUp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.signup')),
            ],
        ),
        migrations.CreateModel(
            name='EProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.TextField(default='')),
                ('SignUp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.signup')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckStatus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.checkstatus')),
                ('Eprogram', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.eprogram')),
            ],
        ),
        migrations.CreateModel(
            name='IndexStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField(default='')),
                ('SignUp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.signup')),
            ],
        ),
    ]
