# Generated by Django 3.1.6 on 2021-08-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0007_checkstatus_eprogram_indexstatus_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Height', models.FloatField(default='')),
                ('Weight', models.FloatField(default='')),
                ('BMITotal', models.FloatField(default='')),
                ('BMIResult', models.TextField(default='')),
                ('SignUp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BMIList.signup')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkstatus',
            name='SignUp',
        ),
        migrations.RemoveField(
            model_name='eprogram',
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.RemoveField(
            model_name='indexstatus',
            name='SignUp',
        ),
        migrations.RemoveField(
            model_name='record',
            name='CheckStatus',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Eprogram',
        ),
        migrations.DeleteModel(
            name='CheckStatus',
        ),
        migrations.DeleteModel(
            name='EProgram',
        ),
        migrations.DeleteModel(
            name='IndexStatus',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
