# Generated by Django 3.1.6 on 2021-08-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0009_remove_signup_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='psw',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sex',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='---', max_length=20, verbose_name='sex'),
        ),
    ]
