# Generated by Django 3.1.6 on 2021-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0012_auto_20210823_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='meyl',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='sex',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='---', max_length=20),
        ),
    ]
